# Site settings
title: Daniel Smith
description: >
  Developer extraordinaire

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://getabetterpic.com" # the base hostname & protocol for your site

author:
  fullname: Daniel Smith
  googleplus: https://www.google.com/+DanielSmithgetabetterpic
  github: getabetterpic
  twitter: getabetterpic
  disqus: getabetterpic

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: redcarpet
slug: '/:year/:month/:day/:title'
